<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260419090548 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(
        Schema $schema,
    ): void {
        $this->addSql('CREATE TABLE foo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
    }

    public function down(
        Schema $schema,
    ): void {
        $this->addSql('DROP TABLE foo');
    }
}
