imports:
    - { resource: 'vyse.yaml' }

services:
    _defaults:
        autowire: true      
        autoconfigure: true 

    App\:
        resource: '../app/'

    App\Fixtures\:
        resource: '../app/Fixtures/'
        tags: ['doctrine.fixture.orm']
