services:
    _defaults:
        autowire: true      
        autoconfigure: true 

    Vyse\Framework\:
        resource: '../src/'

    Vyse\Framework\Twig\Compiler\ComponentSyntaxLoader:
        decorates: 'twig.loader.native_filesystem'
        arguments:
            $innerLoader: '@.inner'
